version: '2.4'

services:

  database:
    image: mysql:8.0.16
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    networks:
      - app-network
    volumes:
      - ${MNT_DIR}/my.cnf:/etc/mysql/my.cnf
      - ${MNT_DIR}/db-data/:/var/lib/mysql/
      - ${MNT_DIR}/db-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpcc_bench
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpassword
    ports:
      - "3307:3306"
    mem_limit: ${DB_MEM}MB
    memswap_limit: -1
    mem_swappiness: 100
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 2s
      retries: 10

  php:
    build:
      context: ${MNT_DIR}
      dockerfile: ${MNT_DIR}/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - ${MNT_DIR}/webpage/:/srv/www/api/
      - ${MNT_DIR}/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${MNT_DIR}/php-log/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=tpcc_bench
    networks:
      - app-network
    mem_limit: ${PHP_MEM}MB
    memswap_limit: -1
    mem_swappiness: 100
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx:
    image: nginx:1.17.1
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    ports:
      - "8080:80"
    volumes:
      - ${MNT_DIR}/webpage/:/srv/www/api/
      - ${MNT_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${MNT_DIR}/nginx-log/:/var/log/nginx/
    networks:
      - app-network
    command: ["nginx", "-g", "daemon off;"]
    mem_limit: ${NGINX_MEM}MB
    memswap_limit: -1
    mem_swappiness: 100
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Docker Networks
networks:
  app-network:
    driver: bridge
